name: CI

on: [push, pull_request]

jobs:

  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conda Envs
      uses: actions/cache@v2
      with:
        path: |
          ~/miniconda3
          build/*.txt
        key: ${{ runner.OS }}-conda-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'Makefile*') }}
        restore-keys: |
          ${{ runner.OS }}-conda-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'Makefile*') }}

    - name: make conda
      run:
        if [[ -e build/envs.txt ]]; then touch build/envs.txt; fi;
        if [[ -e build/deps.txt ]]; then touch build/deps.txt; fi;
        make conda

    - name: make lint
      run: make lint

    - name: make mypy
      run: make mypy

    - name: make test
      run: make test

    - name: make test_compat
      run: make test_compat

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conda Envs
      uses: actions/cache@v2
      with:
        path: |
          ~/miniconda3
          build/*.txt
        key: ${{ runner.OS }}-conda-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'Makefile*') }}
        restore-keys: |
          ${{ runner.OS }}-conda-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'Makefile*') }}

    - name: brew install mercurial
      run: brew install mercurial

    - name: make conda
      run:
        if [[ -e build/envs.txt ]]; then touch build/envs.txt; fi;
        if [[ -e build/deps.txt ]]; then touch build/deps.txt; fi;
        make conda

    - name: make lint
      run: make lint

    - name: make mypy
      run: make mypy

    - name: make test
      run: make test
